import type { WorkspaceMode } from "@/lib/types";
import type { TourModule } from "../types";

/**
 * S4 — "Reports" (Sales track; mode = Sales or Both; builds on S3).
 *
 * The analytics layer: funnel, velocity, win rate, and forecast dashboards, plus
 * the AI briefing that reads the numbers and tells the story (pipeline
 * narrative / pulse).
 *
 * Anchors (data-tour selectors on /reports):
 *   - [data-tour="reports-kpis"]     → the win-rate / KPI row
 *   - [data-tour="reports-briefing"] → the "Pipeline Health AI Briefing" card
 *
 * Mode-gating: every step is showForModes ["sales","both"].
 */

const SALES: WorkspaceMode[] = ["sales", "both"];

const present = (selector: string) => () =>
  typeof document !== "undefined" && document.querySelector(selector) !== null;

export const moduleS4Reports: TourModule = {
  id: "module-s4-reports",
  title: "Reports",
  description:
    "See the whole picture: funnel, velocity, win rate, and forecast — with an AI briefing that reads it for you.",
  steps: [
    {
      id: "analytics-dashboards",
      title: "Your analytics at a glance",
      showForModes: SALES,
      whyThisExists:
        "Once deals are flowing, you need to see the shape of the business: how many convert, how fast they move, and what's coming. Reports turns your pipeline into funnel, velocity, and forecast dashboards.",
      prerequisiteCheck: {
        label: "You've run outreach and opened Reports.",
        verify: present('[data-tour="reports-kpis"]'),
        nudge: "Open Reports from the sidebar (Sales workspaces) to follow along.",
      },
      anchor: { selector: '[data-tour="reports-kpis"]', placement: "auto", padding: 8 },
      actionGuidance:
        "Start with the KPI row — win rate, pipeline value, and the headline numbers. Scroll for the funnel (conversion by stage), velocity (days per stage), and revenue forecast.",
      whatJustHappened:
        "You're looking at your business, measured. Every deal you've worked in the earlier modules rolls up into these charts.",
      forwardReference:
        "Numbers alone don't decide anything — so the AI reads them for you, which is the next step.",
      checkpoint: { confirmLabel: "Got it → Next" },
    },
    {
      id: "ai-briefing",
      title: "AI reads your numbers",
      showForModes: SALES,
      whyThisExists:
        "Dashboards show what happened; the AI briefing tells you what it means and what to do. It turns your funnel and velocity into a plain-language narrative with momentum and risk called out.",
      prerequisiteCheck: {
        label: "The AI briefing card is on the page.",
        verify: present('[data-tour="reports-briefing"]'),
      },
      anchor: { selector: '[data-tour="reports-briefing"]', placement: "auto", padding: 8 },
      actionGuidance:
        "Read the Pipeline Health briefing at the top. It summarizes where the business stands, whether momentum is accelerating or stalling, and where to focus — regenerate it anytime for a fresh read.",
      whatJustHappened:
        "You've completed the Sales track. From leads to deals to automated outreach to a narrated forecast, your workspace now runs a full sales motion.",
      forwardReference:
        "For everyday questions between reports, remember Nova via ⌘K — \"what's my win rate this quarter?\" — the front door you met in Module 1.",
      checkpoint: { confirmLabel: "Finish" },
      aiTip: {
        text: "AI tip: the pipeline narrative / pulse turns your metrics into a written brief — momentum, risks, and the story behind the win rate — generated by Claude from your live deal data.",
        prompt: "Explain the AI pipeline narrative/pulse that turns funnel and velocity metrics into a plain-language brief.",
      },
    },
  ],
};
