import type {
  Contact, Deal, Agent, ActivityEvent, KPI,
} from "./types";

// ─── KPIs ────────────────────────────────────────────────────────────────────
export const mockKPIs: KPI[] = [
  {
    id: "k1",
    label: "Total Revenue",
    value: "$2.4M",
    delta: "+18.2%",
    deltaType: "positive",
    icon: "dollar",
    sparkData: [30, 45, 38, 55, 60, 72, 68, 80, 95, 88, 102, 115],
  },
  {
    id: "k2",
    label: "Active Deals",
    value: "148",
    delta: "+12",
    deltaType: "positive",
    icon: "briefcase",
    sparkData: [90, 95, 88, 102, 110, 118, 125, 120, 132, 138, 142, 148],
  },
  {
    id: "k3",
    label: "ML Lead Accuracy",
    value: "94.7%",
    delta: "+2.1%",
    deltaType: "positive",
    icon: "brain",
    sparkData: [88, 89, 90, 89, 91, 92, 91, 93, 93, 94, 95, 94.7],
  },
  {
    id: "k4",
    label: "Agents Running",
    value: "6 / 8",
    delta: "2 idle",
    deltaType: "neutral",
    icon: "bot",
    sparkData: [4, 5, 6, 5, 7, 6, 8, 7, 6, 8, 7, 6],
  },
];

// ─── Contacts ────────────────────────────────────────────────────────────────
export const mockContacts: Contact[] = [
  {
    id: "c1",
    name: "Sarah Chen",
    email: "s.chen@nexlabs.io",
    company: "NexLabs",
    role: "VP of Engineering",
    avatar: "SC",
    status: "customer",
    mlScore: {
      value: 92,
      label: "hot",
      trend: "up",
      signals: ["High engagement", "Recent demo request", "Budget confirmed"],
    },
    semanticTags: [
      { label: "Enterprise Buyer", confidence: 0.97, color: "indigo" },
      { label: "Decision Maker", confidence: 0.91, color: "emerald" },
      { label: "Technical", confidence: 0.88, color: "indigo" },
    ],
    lastActivity: "2 hours ago",
    deals: 3,
    revenue: 48000,
    createdAt: "2024-09-15",
  },
  {
    id: "c2",
    name: "Marcus Webb",
    email: "m.webb@strataform.com",
    company: "StrataForm",
    role: "CEO",
    avatar: "MW",
    status: "prospect",
    mlScore: {
      value: 78,
      label: "warm",
      trend: "up",
      signals: ["Multiple page visits", "Downloaded whitepaper"],
    },
    semanticTags: [
      { label: "C-Suite", confidence: 0.99, color: "amber" },
      { label: "Growth Stage", confidence: 0.82, color: "emerald" },
    ],
    lastActivity: "Yesterday",
    deals: 1,
    revenue: 0,
    createdAt: "2024-11-02",
  },
  {
    id: "c3",
    name: "Priya Nair",
    email: "priya@cloudvault.ai",
    company: "CloudVault AI",
    role: "Head of Ops",
    avatar: "PN",
    status: "lead",
    mlScore: {
      value: 61,
      label: "warm",
      trend: "stable",
      signals: ["Email opened x4", "LinkedIn profile viewed"],
    },
    semanticTags: [
      { label: "Operations Focus", confidence: 0.85, color: "indigo" },
      { label: "AI-Adjacent", confidence: 0.79, color: "emerald" },
    ],
    lastActivity: "3 days ago",
    deals: 0,
    revenue: 0,
    createdAt: "2025-01-18",
  },
  {
    id: "c4",
    name: "James Okafor",
    email: "jokafor@meridian-cap.com",
    company: "Meridian Capital",
    role: "CFO",
    avatar: "JO",
    status: "customer",
    mlScore: {
      value: 88,
      label: "hot",
      trend: "stable",
      signals: ["Annual contract", "Referral source", "High NPS"],
    },
    semanticTags: [
      { label: "Finance Sector", confidence: 0.96, color: "amber" },
      { label: "Expansion Ready", confidence: 0.73, color: "emerald" },
      { label: "Decision Maker", confidence: 0.94, color: "indigo" },
    ],
    lastActivity: "1 day ago",
    deals: 2,
    revenue: 120000,
    createdAt: "2024-06-20",
  },
  {
    id: "c5",
    name: "Lena Kovacs",
    email: "lena.k@solvio.eu",
    company: "Solvio EU",
    role: "Product Director",
    avatar: "LK",
    status: "prospect",
    mlScore: {
      value: 44,
      label: "cold",
      trend: "down",
      signals: ["No reply in 14 days", "Unsubscribed from one campaign"],
    },
    semanticTags: [
      { label: "European Market", confidence: 0.91, color: "indigo" },
      { label: "Risk: Churn", confidence: 0.65, color: "rose" },
    ],
    lastActivity: "2 weeks ago",
    deals: 1,
    revenue: 0,
    createdAt: "2025-02-01",
  },
  {
    id: "c6",
    name: "Dmitri Volkov",
    email: "d.volkov@axion-sys.com",
    company: "Axion Systems",
    role: "CTO",
    avatar: "DV",
    status: "customer",
    mlScore: {
      value: 95,
      label: "hot",
      trend: "up",
      signals: ["Upsell candidate", "High feature adoption", "Champion user"],
    },
    semanticTags: [
      { label: "Power User", confidence: 0.98, color: "emerald" },
      { label: "Technical", confidence: 0.95, color: "indigo" },
      { label: "Upsell Ready", confidence: 0.88, color: "emerald" },
    ],
    lastActivity: "30 min ago",
    deals: 4,
    revenue: 240000,
    createdAt: "2024-03-10",
  },
];

// ─── Deals / Pipeline ────────────────────────────────────────────────────────
export const mockDeals: Deal[] = [
  {
    id: "d1",
    title: "NexLabs Enterprise Suite",
    company: "NexLabs",
    contactName: "Sarah Chen",
    value: 48000,
    stage: "negotiation",
    mlWinProbability: 87,
    expectedClose: "Apr 30, 2026",
    assignedAgent: "Pipeline Optimizer",
    notes: "Legal review in progress. Champion confirmed budget.",
    createdAt: "2026-02-10",
  },
  {
    id: "d2",
    title: "StrataForm Pilot",
    company: "StrataForm",
    contactName: "Marcus Webb",
    value: 12000,
    stage: "proposal",
    mlWinProbability: 62,
    expectedClose: "May 15, 2026",
    assignedAgent: "Email Composer",
    notes: "Proposal sent. Awaiting feedback from board.",
    createdAt: "2026-03-01",
  },
  {
    id: "d3",
    title: "Meridian Capital Renewal",
    company: "Meridian Capital",
    contactName: "James Okafor",
    value: 120000,
    stage: "qualified",
    mlWinProbability: 91,
    expectedClose: "Jun 1, 2026",
    assignedAgent: "Lead Scorer",
    notes: "Annual renewal. Expansion to 5 more seats discussed.",
    createdAt: "2026-01-05",
  },
  {
    id: "d4",
    title: "Axion Systems Upsell",
    company: "Axion Systems",
    contactName: "Dmitri Volkov",
    value: 65000,
    stage: "discovery",
    mlWinProbability: 74,
    expectedClose: "May 30, 2026",
    assignedAgent: "Semantic Sorter",
    notes: "Interested in analytics add-on module.",
    createdAt: "2026-04-01",
  },
  {
    id: "d5",
    title: "CloudVault AI Starter",
    company: "CloudVault AI",
    contactName: "Priya Nair",
    value: 8400,
    stage: "discovery",
    mlWinProbability: 45,
    expectedClose: "Jun 20, 2026",
    assignedAgent: "Sentiment Analyzer",
    notes: "Early stage. Needs more qualification.",
    createdAt: "2026-04-10",
  },
  {
    id: "d6",
    title: "Solvio EU Enterprise",
    company: "Solvio EU",
    contactName: "Lena Kovacs",
    value: 30000,
    stage: "closed_lost",
    mlWinProbability: 0,
    expectedClose: "Mar 31, 2026",
    assignedAgent: "Pipeline Optimizer",
    notes: "Lost to competitor. Price was the primary objection.",
    createdAt: "2025-12-01",
  },
  {
    id: "d7",
    title: "NexLabs Analytics Module",
    company: "NexLabs",
    contactName: "Sarah Chen",
    value: 18000,
    stage: "closed_won",
    mlWinProbability: 100,
    expectedClose: "Apr 5, 2026",
    assignedAgent: "Pipeline Optimizer",
    notes: "Signed. Onboarding scheduled for Apr 12.",
    createdAt: "2026-03-15",
  },
];

// ─── Agents ──────────────────────────────────────────────────────────────────
export const mockAgents: Agent[] = [
  {
    id: "a1",
    name: "Semantic Sorter",
    type: "semantic_sorter",
    status: "active",
    description:
      "Uses sentence-transformer embeddings to classify and tag contacts by intent, industry, role, and buying signals. Continuously re-ranks your contact list.",
    model: "all-MiniLM-L6-v2 + GPT-4o",
    accuracy: 96.4,
    tasksToday: 312,
    lastRun: "2 min ago",
    metrics: [
      { label: "Tags Applied Today", value: "1,204", delta: "+89" },
      { label: "Avg Confidence", value: "94.1%", delta: "+0.3%" },
      { label: "Reclassifications", value: "47" },
    ],
    workflow: [
      { id: "w1", label: "New Contact Trigger", type: "trigger", position: { x: 0, y: 0 } },
      { id: "w2", label: "Embed Text (MiniLM)", type: "action", position: { x: 200, y: 0 }, connected: ["w1"] },
      { id: "w3", label: "Cosine Similarity Rank", type: "action", position: { x: 400, y: 0 }, connected: ["w2"] },
      { id: "w4", label: "Confidence > 0.85?", type: "condition", position: { x: 600, y: 0 }, connected: ["w3"] },
      { id: "w5", label: "Apply Semantic Tag", type: "output", position: { x: 800, y: -60 }, connected: ["w4"] },
      { id: "w6", label: "Queue for Review", type: "output", position: { x: 800, y: 60 }, connected: ["w4"] },
    ],
  },
  {
    id: "a2",
    name: "Lead Scorer",
    type: "lead_scorer",
    status: "active",
    description:
      "XGBoost model trained on historical deal outcomes. Scores every contact 0–100 using behavioral signals, firmographic data, and engagement patterns.",
    model: "XGBoost v2 + Feature Store",
    accuracy: 94.7,
    tasksToday: 524,
    lastRun: "8 min ago",
    metrics: [
      { label: "Scores Updated", value: "524", delta: "+112" },
      { label: "Hot Leads", value: "23", delta: "+5" },
      { label: "Model F1 Score", value: "0.947" },
    ],
    workflow: [
      { id: "w1", label: "Behavior Event", type: "trigger", position: { x: 0, y: 0 } },
      { id: "w2", label: "Feature Extraction", type: "action", position: { x: 200, y: 0 }, connected: ["w1"] },
      { id: "w3", label: "XGBoost Inference", type: "action", position: { x: 400, y: 0 }, connected: ["w2"] },
      { id: "w4", label: "Update Contact Score", type: "output", position: { x: 600, y: 0 }, connected: ["w3"] },
    ],
  },
  {
    id: "a3",
    name: "Email Composer",
    type: "email_composer",
    status: "processing",
    description:
      "Generates hyper-personalized outreach emails using contact context, semantic tags, and deal stage. Adapts tone to role and industry.",
    model: "GPT-4o (fine-tuned)",
    accuracy: 91.2,
    tasksToday: 87,
    lastRun: "Just now",
    metrics: [
      { label: "Emails Drafted", value: "87", delta: "+22" },
      { label: "Open Rate (7d)", value: "48.3%", delta: "+6.1%" },
      { label: "Reply Rate (7d)", value: "22.1%", delta: "+3.4%" },
    ],
    workflow: [
      { id: "w1", label: "Deal Stage Change", type: "trigger", position: { x: 0, y: 0 } },
      { id: "w2", label: "Fetch Contact Context", type: "action", position: { x: 200, y: 0 }, connected: ["w1"] },
      { id: "w3", label: "Compose with GPT-4o", type: "action", position: { x: 400, y: 0 }, connected: ["w2"] },
      { id: "w4", label: "Human Review?", type: "condition", position: { x: 600, y: 0 }, connected: ["w3"] },
      { id: "w5", label: "Send via Gmail API", type: "output", position: { x: 800, y: -60 }, connected: ["w4"] },
      { id: "w6", label: "Hold for Approval", type: "output", position: { x: 800, y: 60 }, connected: ["w4"] },
    ],
  },
  {
    id: "a4",
    name: "Call Summarizer",
    type: "call_summarizer",
    status: "idle",
    description:
      "Transcribes and summarizes sales calls. Extracts action items, objections, sentiment, and next steps. Updates contact timeline automatically.",
    model: "Whisper Large v3 + Claude 3.5",
    accuracy: 97.1,
    tasksToday: 14,
    lastRun: "1 hour ago",
    metrics: [
      { label: "Calls Processed", value: "14", delta: "+3" },
      { label: "Avg Summary Time", value: "23s" },
      { label: "Action Items Extracted", value: "41", delta: "+8" },
    ],
    workflow: [
      { id: "w1", label: "Call Recording Upload", type: "trigger", position: { x: 0, y: 0 } },
      { id: "w2", label: "Whisper Transcription", type: "action", position: { x: 200, y: 0 }, connected: ["w1"] },
      { id: "w3", label: "Extract Key Points", type: "action", position: { x: 400, y: 0 }, connected: ["w2"] },
      { id: "w4", label: "Update Contact Timeline", type: "output", position: { x: 600, y: 0 }, connected: ["w3"] },
    ],
  },
  {
    id: "a5",
    name: "Pipeline Optimizer",
    type: "pipeline_optimizer",
    status: "active",
    description:
      "Monitors deal velocity and predicts stalls. Recommends next best actions using reinforcement learning from historical pipeline data.",
    model: "RL Policy + LightGBM",
    accuracy: 89.3,
    tasksToday: 201,
    lastRun: "15 min ago",
    metrics: [
      { label: "Stalls Detected", value: "7", delta: "+2" },
      { label: "Actions Recommended", value: "201" },
      { label: "Win Rate Lift", value: "+14.2%" },
    ],
    workflow: [
      { id: "w1", label: "Daily Pipeline Scan", type: "trigger", position: { x: 0, y: 0 } },
      { id: "w2", label: "Velocity Analysis", type: "action", position: { x: 200, y: 0 }, connected: ["w1"] },
      { id: "w3", label: "Stall Prediction", type: "action", position: { x: 400, y: 0 }, connected: ["w2"] },
      { id: "w4", label: "Generate Action Plan", type: "output", position: { x: 600, y: 0 }, connected: ["w3"] },
    ],
  },
  {
    id: "a6",
    name: "Sentiment Analyzer",
    type: "sentiment_analyzer",
    status: "active",
    description:
      "Analyzes email threads, call transcripts, and support tickets to gauge contact sentiment. Flags at-risk accounts before churn occurs.",
    model: "RoBERTa fine-tuned + GPT-4o-mini",
    accuracy: 93.8,
    tasksToday: 388,
    lastRun: "5 min ago",
    metrics: [
      { label: "Signals Analyzed", value: "388", delta: "+54" },
      { label: "At-Risk Flagged", value: "3", delta: "+1" },
      { label: "Avg Sentiment Score", value: "0.74" },
    ],
    workflow: [
      { id: "w1", label: "New Email / Ticket", type: "trigger", position: { x: 0, y: 0 } },
      { id: "w2", label: "RoBERTa Inference", type: "action", position: { x: 200, y: 0 }, connected: ["w1"] },
      { id: "w3", label: "Sentiment < 0.4?", type: "condition", position: { x: 400, y: 0 }, connected: ["w2"] },
      { id: "w4", label: "Flag At-Risk + Alert", type: "output", position: { x: 600, y: -60 }, connected: ["w3"] },
      { id: "w5", label: "Update Sentiment Log", type: "output", position: { x: 600, y: 60 }, connected: ["w3"] },
    ],
  },
];

// ─── Activity Feed ────────────────────────────────────────────────────────────
export const mockActivity: ActivityEvent[] = [
  {
    id: "ev1",
    type: "contact_scored",
    agentName: "Lead Scorer",
    description: "Re-scored Dmitri Volkov → 95 (was 88)",
    meta: "Upsell signals detected",
    timestamp: "2 min ago",
    severity: "success",
  },
  {
    id: "ev2",
    type: "tag_applied",
    agentName: "Semantic Sorter",
    description: "Tagged 12 new contacts with 'Enterprise Buyer'",
    meta: "Avg confidence: 93.4%",
    timestamp: "5 min ago",
    severity: "info",
  },
  {
    id: "ev3",
    type: "email_sent",
    agentName: "Email Composer",
    description: "Drafted follow-up for Marcus Webb",
    meta: "Proposal stage · Human review pending",
    timestamp: "9 min ago",
    severity: "info",
  },
  {
    id: "ev4",
    type: "deal_moved",
    agentName: "Pipeline Optimizer",
    description: "NexLabs Enterprise Suite → Negotiation",
    meta: "Win probability: 87%",
    timestamp: "18 min ago",
    severity: "success",
  },
  {
    id: "ev5",
    type: "agent_run",
    agentName: "Sentiment Analyzer",
    description: "Flagged Lena Kovacs as at-risk",
    meta: "Sentiment score dropped to 0.31",
    timestamp: "22 min ago",
    severity: "warning",
  },
  {
    id: "ev6",
    type: "call_summarized",
    agentName: "Call Summarizer",
    description: "Processed 38-min call with James Okafor",
    meta: "3 action items extracted",
    timestamp: "1 hour ago",
    severity: "info",
  },
  {
    id: "ev7",
    type: "model_updated",
    agentName: "Lead Scorer",
    description: "XGBoost model retrained on 1,204 new samples",
    meta: "F1: 0.947 → 0.951 (+0.4%)",
    timestamp: "3 hours ago",
    severity: "success",
  },
  {
    id: "ev8",
    type: "deal_moved",
    agentName: "Pipeline Optimizer",
    description: "Detected stall: Solvio EU (21 days inactive)",
    meta: "Recommended: Re-engagement sequence",
    timestamp: "4 hours ago",
    severity: "warning",
  },
];

// ─── Revenue Chart Data ───────────────────────────────────────────────────────
export const revenueChartData = [
  { month: "Nov", revenue: 180000, deals: 22 },
  { month: "Dec", revenue: 195000, deals: 25 },
  { month: "Jan", revenue: 210000, deals: 28 },
  { month: "Feb", revenue: 225000, deals: 31 },
  { month: "Mar", revenue: 260000, deals: 35 },
  { month: "Apr", revenue: 298000, deals: 38 },
];

export const agentAccuracyData = [
  { day: "Mon", semantic: 95.1, leadScore: 93.2, sentiment: 91.8 },
  { day: "Tue", semantic: 95.8, leadScore: 94.0, sentiment: 92.5 },
  { day: "Wed", semantic: 96.2, leadScore: 93.8, sentiment: 93.1 },
  { day: "Thu", semantic: 95.9, leadScore: 94.5, sentiment: 93.8 },
  { day: "Fri", semantic: 96.4, leadScore: 94.7, sentiment: 93.8 },
];
